# templates/deployment.yaml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-redis-deployment
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.redis.replicaCount }}
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      # 设置亲和度:只在slave-node2上进行实验,将数据库等都放在slave-node3上来避免和应用pods发生资源争夺。
      nodeSelector:
        kubernetes.io/hostname: "slave-node3"
      containers:
        - name: redis
          image: {{ .Values.redis.image }}
          ports:
            - containerPort: 6379
          resources: {{ toYaml .Values.redis.resources | nindent 12 }}