# stress-test-web-chart/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
  namespace: {{ .Release.Namespace }}
data:
  SPRING_DATASOURCE_URL: {{ .Values.configMap.SPRING_DATASOURCE_URL | quote }}
  SPRING_DATASOURCE_DRIVER_CLASS_NAME: {{ .Values.configMap.SPRING_DATASOURCE_DRIVER_CLASS_NAME | quote }}
  SPRING_REDIS_HOST: {{ .Values.configMap.SPRING_REDIS_HOST | quote }}
  SPRING_REDIS_PORT: {{ .Values.configMap.SPRING_REDIS_PORT | quote }}
  # Add other non-sensitive configuration here
