# stress-test-web-chart/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-deployment
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.replicasCount }}
  selector:
    matchLabels:
      app: stress-test-web
  template:
    metadata:
      labels:
        app: stress-test-web
    spec:
      {{- if eq .Values.resourceConfiguration "flexible" }}
      # 柔性调度框架调整
      schedulerName: rescheduler
      {{- end }}
      # 设置亲和度:只在slave-node2上进行实验
      nodeSelector:
        kubernetes.io/hostname: "slave-node2"
      containers:
        - name: stress-test-web
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          ports:
            - containerPort: 8090
          env:
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Name }}-configmap
                  key: SPRING_DATASOURCE_URL
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-secrets
                  key: SPRING_DATASOURCE_USERNAME
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-secrets
                  key: SPRING_DATASOURCE_PASSWORD
            - name: SPRING_DATASOURCE_DRIVER_CLASS_NAME
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Name }}-configmap
                  key: SPRING_DATASOURCE_DRIVER_CLASS_NAME
            - name: SPRING_REDIS_HOST
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Name }}-configmap
                  key: SPRING_REDIS_HOST
            - name: SPRING_REDIS_PORT
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Name }}-configmap
                  key: SPRING_REDIS_PORT
          imagePullPolicy: IfNotPresent
          {{- if eq .Values.resourceConfiguration "normal" }}
          resources:
            requests:
              memory: "500Mi"
              cpu: "0.5"
            limits:
              memory: "800Mi"
              cpu: "0.8"
          {{- else if eq .Values.resourceConfiguration "flexible" }}
          resources:
            requests:
              memory: "1Mi"
              cpu: "1m"
            limits:
              memory: "500Mi"
              cpu: "0.5"
          {{- end }}