apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: {{ .Release.Name }}-destination-rule
spec:
  host: {{ .Release.Name }}-service
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
