# stress-test-web-chart/templates/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "stress-test-web-chart.fullname" . }}-secret
type: Opaque
data:
  springDatasourcePassword: {{ .Values.config.springDatasourcePassword | b64enc | quote }}
