# stress-test-web-chart/templates/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secrets
  namespace: {{ .Release.Namespace }}
data:
  SPRING_DATASOURCE_USERNAME: {{ .Values.secrets.SPRING_DATASOURCE_USERNAME | b64enc | quote }}
  SPRING_DATASOURCE_PASSWORD: {{ .Values.secrets.SPRING_DATASOURCE_PASSWORD | b64enc | quote }}
  # Add other sensitive information here
