apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-service
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: stress-test-web
  ports:
    - protocol: TCP
      port: 8090
      targetPort: 8090
      nodePort: 30341
  type: LoadBalancer