# templates/deployment.yaml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-mysql-deployment
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.replicaCount}}
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      # 设置亲和度:只在slave-node2上进行实验,将数据库等都放在slave-node3上来避免和应用pods发生资源争夺。
      nodeSelector:
        kubernetes.io/hostname: "slave-node2"
      containers:
        - name: mysql
          image: {{ .Values.mysql.image }}
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-mysql-secret
                  key: root-password
            - name: MYSQL_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Name }}-mysql-config
                  key: MYSQL_DATABASE
          ports:
            - containerPort: 3306
          resources: {{ toYaml .Values.resources | nindent 12 }}