# templates/secret.yaml

apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-mysql-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  root-password: {{ .Values.mysql.rootPassword }}