apiVersion: v1
kind: Service
metadata:
  name: stress-test-web-service
  namespace: lry
spec:
  selector:
    app: stress-test-web
  ports:
    - protocol: TCP
      port: 8090
      targetPort: 8090
      nodePort: 30341
  type: LoadBalancer # 将类型改为 LoadBalancer