apiVersion: v1
kind: Service
metadata:
  name: stress-test-web-service
spec:
  selector:
    app: stress-test-web
  ports:
    - protocol: TCP
      port: 8090
      targetPort: 8090
  type: NodePort
